name: Homepage - quality gate

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'apps/homepage/**'
      - 'packages/app-config/**'
      - '.github/actions/checkout-remote-actions/action.yml'
      - '.github/workflows/homepage-quality-gate.yml'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel build runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Run ESLint
        run: |
          echo "Run ESLint"

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel build runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Run Stylelint
        run: |
          echo "Run Stylelint"